-- attributes.sql - generated by Enablement_MTA_Agent for build 20260929-165448. Do not edit by hand:
-- this is the exact query the build ran (mta_agent/core/extract.py).
-- Source table: "SAND_INTOUCH_RAW_DB"."AD-HOC"."OMNICHANNEL_MTA_TAIHO_LONSURF"
-- Purpose: HCP specialty / affiliation / journey stage for the dashboard filters (only when mapped).

SELECT "NPI"::VARCHAR, "HCP_SPECIALTY", NULL, "HCP_CURRENT_JOURNEY_STAGE" FROM OMNICHANNEL_MTA_TAIHO_LONSURF;
