-- health.sql - generated by Enablement_MTA_Agent for build 20260929-165448. Do not edit by hand:
-- this is the exact query the build ran (mta_agent/core/extract.py).
-- Source table: "SAND_INTOUCH_RAW_DB"."AD-HOC"."OMNICHANNEL_MTA_TAIHO_LONSURF"
-- Purpose: Row counts, null counts, date ranges and HCP counts used by the validation checks.

SELECT
            COUNT(*) AS total_rows,
            COUNT_IF("DATA_SOURCE" IN ('PLD', 'TARGET_ONLY')) AS media_rows,
            COUNT_IF("DATA_SOURCE" IN ('PRESCRIPTION')) AS rx_rows,
            COUNT_IF("DATA_SOURCE" IN ('PLD', 'TARGET_ONLY') AND "NPI" IS NULL) AS media_null_npi,
            COUNT_IF("DATA_SOURCE" IN ('PLD', 'TARGET_ONLY') AND "DATE" IS NULL) AS media_null_date,
            COUNT_IF("DATA_SOURCE" IN ('PLD', 'TARGET_ONLY') AND "CHANNEL" IS NULL) AS media_null_channel,
            COUNT_IF("DATA_SOURCE" IN ('PRESCRIPTION') AND "NPI" IS NULL) AS rx_null_npi,
            COUNT_IF("DATA_SOURCE" IN ('PRESCRIPTION') AND "DATE" IS NULL) AS rx_null_date,
            MIN(IFF("DATA_SOURCE" IN ('PLD', 'TARGET_ONLY'), "DATE", NULL)) AS media_min_date,
            MAX(IFF("DATA_SOURCE" IN ('PLD', 'TARGET_ONLY'), "DATE", NULL)) AS media_max_date,
            MIN(IFF("DATA_SOURCE" IN ('PRESCRIPTION'), "DATE", NULL)) AS rx_min_date,
            MAX(IFF("DATA_SOURCE" IN ('PRESCRIPTION'), "DATE", NULL)) AS rx_max_date,
            COUNT(DISTINCT IFF("DATA_SOURCE" IN ('PLD', 'TARGET_ONLY'), "NPI", NULL)) AS media_hcps,
            COUNT(DISTINCT IFF("DATA_SOURCE" IN ('PRESCRIPTION'), "NPI", NULL)) AS rx_hcps
          FROM "SAND_INTOUCH_RAW_DB"."AD-HOC"."OMNICHANNEL_MTA_TAIHO_LONSURF" WHERE TRUE;
