-- media_month.sql - generated by Enablement_MTA_Agent for build 20260929-165448. Do not edit by hand:
-- this is the exact query the build ran (mta_agent/core/extract.py).
-- Source table: "SAND_INTOUCH_RAW_DB"."AD-HOC"."OMNICHANNEL_MTA_TAIHO_LONSURF"
-- Purpose: Distinct reached / engaged HCPs per month (per channel and in total). Feeds KPI sparklines and deltas.

SELECT DATE_TRUNC('month', "DATE")::DATE AS month, "CHANNEL" AS channel,
            COUNT(DISTINCT "NPI") AS reached_hcps,
            COUNT(DISTINCT IFF(COALESCE("IS_HCP_ENGAGED", FALSE), "NPI", NULL)) AS engaged_hcps,
            GROUPING("CHANNEL") AS is_total
          FROM "SAND_INTOUCH_RAW_DB"."AD-HOC"."OMNICHANNEL_MTA_TAIHO_LONSURF"
          WHERE "DATA_SOURCE" IN ('PLD', 'TARGET_ONLY') AND "NPI" IS NOT NULL AND "DATE" IS NOT NULL AND "CHANNEL" IS NOT NULL
          GROUP BY GROUPING SETS ((DATE_TRUNC('month', "DATE"), "CHANNEL"), (DATE_TRUNC('month', "DATE")));
