-- rx.sql - generated by Enablement_MTA_Agent for build 20260929-165448. Do not edit by hand:
-- this is the exact query the build ran (mta_agent/core/extract.py).
-- Source table: "SAND_INTOUCH_RAW_DB"."AD-HOC"."OMNICHANNEL_MTA_TAIHO_LONSURF"
-- Purpose: Scripts per HCP per month for the three script-metric slots. Feeds every attribution model and script KPI.

SELECT "NPI"::VARCHAR AS npi, DATE_TRUNC('month', "DATE")::DATE AS month, MIN("DATE") AS first_dt,
            SUM(COALESCE("TRX", 0)) AS trx, SUM(COALESCE("NBRX", 0)) AS nbrx, SUM(COALESCE("NRX", 0)) AS nrx
          FROM "SAND_INTOUCH_RAW_DB"."AD-HOC"."OMNICHANNEL_MTA_TAIHO_LONSURF"
          WHERE "DATA_SOURCE" IN ('PRESCRIPTION') AND "NPI" IS NOT NULL AND "DATE" IS NOT NULL
          GROUP BY 1, 2;
