-- touches.sql - generated by Enablement_MTA_Agent for build 20260929-165448. Do not edit by hand:
-- this is the exact query the build ran (mta_agent/core/extract.py).
-- Source table: "SAND_INTOUCH_RAW_DB"."AD-HOC"."OMNICHANNEL_MTA_TAIHO_LONSURF"
-- Purpose: One row per HCP x channel x partner: first/last touch date, reached and engaged flags. Feeds HCP paths, first/last touch, reach/engagement KPIs and the partner table.

SELECT "NPI"::VARCHAR AS npi, "CHANNEL" AS channel, COALESCE("PARTNER", 'Unknown') AS partner,
            MIN("DATE") AS first_dt, MAX("DATE") AS last_dt, BOOLOR_AGG(COALESCE("IS_HCP_REACHED", FALSE)) AS reached,
            BOOLOR_AGG(COALESCE("IS_HCP_ENGAGED", FALSE)) AS engaged,
            MIN(IFF(COALESCE("IS_HCP_ENGAGED", FALSE), "DATE", NULL)) AS first_eng_dt
          FROM "SAND_INTOUCH_RAW_DB"."AD-HOC"."OMNICHANNEL_MTA_TAIHO_LONSURF"
          WHERE "DATA_SOURCE" IN ('PLD', 'TARGET_ONLY') AND "NPI" IS NOT NULL AND "DATE" IS NOT NULL AND "CHANNEL" IS NOT NULL
          GROUP BY 1, 2, 3;
